import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Navigation
    'nav.services': 'Wat we doen',
    'nav.insights': 'Wat we denken',
    'nav.about': 'Wie we zijn',
    'nav.careers': 'Carrières',
    'nav.country': 'Nederland',
    
    // Hero
    'hero.title': 'SAMEN BOUWEN WE',
    'hero.titleHighlight': 'DE TOEKOMST',
    'hero.subtitle': 'Schaalbare Softwareoplossingen',
    'hero.description': 'We helpen klanten prioriteit te geven aan bedrijfsstrategie, technologische gereedheid en organisatorische gereedheid om sneller waarde te creëren.',
    'hero.cta': 'Bekijk wat we doen',
    
    // Stats
    'stats.title': 'Vertrouwd door Toonaangevende Organisaties',
    'stats.subtitle': 'Ons trackrecord spreekt voor zich',
    'stats.clients.number': '500+',
    'stats.clients.label': 'Klanten Geholpen',
    'stats.clients.desc': 'Door heel Nederland',
    'stats.satisfaction.number': '98%',
    'stats.satisfaction.label': 'Klanttevredenheid',
    'stats.satisfaction.desc': 'Toonaangevend retentiepercentage',
    'stats.projects.number': '250+',
    'stats.projects.label': 'Projecten Opgeleverd',
    'stats.projects.desc': 'Op tijd en binnen budget',
    'stats.experience.number': '15+',
    'stats.experience.label': 'Jaar Ervaring',
    'stats.experience.desc': 'In software engineering',
    
    // Cards
    'cards.report': 'ONDERZOEKSRAPPORT',
    'cards.case': 'CASESTUDIE',
    'cards.card1.title': 'Digitale Transformatie: Van complexiteit beheren tot groei versnellen',
    'cards.card1.desc': 'Digitale transformatie is niet alleen een technologie-strategie—het is een gamechanger voor bedrijfsconcurrentievermogen. Ontdek hoe organisaties snel bewegen om hun voordeel te behouden.',
    'cards.card2.title': 'Moderne Ontwikkeling 2025: De toekomst van agile software engineering',
    'cards.card2.desc': 'Ontwikkelteams, geconfronteerd met complexiteit en snelle verandering, zoeken efficiëntie gecombineerd met innovatie, schaalbaarheid en verbinding.',
    'cards.card3.title': 'Enterprise Oplossingen: Platforms bouwen voor morgen',
    'cards.card3.desc': 'Hoe toonaangevende bedrijven hun legacy systemen transformeren naar moderne, schaalbare platforms die bedrijfswaarde opleveren.',
    'cards.card4.title': 'Innovatie Versneld: Mens-AI samenwerking in software',
    'cards.card4.desc': 'Het snijvlak verkennen van menselijke creativiteit en AI-mogelijkheden om te revolutioneren hoe we softwareoplossingen bouwen.',
    
    // Services Showcase
    'servicesShowcase.tag': 'Onze Expertise',
    'servicesShowcase.title': 'Uitgebreide Softwareoplossingen',
    'servicesShowcase.subtitle': 'Van concept tot implementatie leveren we end-to-end software engineering diensten die innovatie en bedrijfsgroei stimuleren',
    'servicesShowcase.mobile': 'Mobiele App Development',
    'servicesShowcase.mobileDesc': 'Native iOS & Android apps met cutting-edge functies en naadloze UX',
    'servicesShowcase.web': 'Web Development',
    'servicesShowcase.webDesc': 'Moderne, responsieve webapplicaties gebouwd met de nieuwste frameworks',
    'servicesShowcase.cloud': 'Cloud Oplossingen',
    'servicesShowcase.cloudDesc': 'Schaalbare cloud-infrastructuur en migratiediensten',
    'servicesShowcase.ai': 'AI & Machine Learning',
    'servicesShowcase.aiDesc': 'Intelligente oplossingen aangedreven door geavanceerde AI-algoritmes',
    'servicesShowcase.data': 'Data Engineering',
    'servicesShowcase.dataDesc': 'Big data oplossingen en analytics voor datagedreven beslissingen',
    'servicesShowcase.security': 'Cyberbeveiliging',
    'servicesShowcase.securityDesc': 'Enterprise-grade beveiligingsoplossingen om uw assets te beschermen',
    
    // Why Choose Us
    'why.tag': 'Waarom TEKFINITY Kiezen',
    'why.title': 'Excellentie in Elke Regel Code',
    'why.subtitle': 'We schrijven niet alleen code—we creëren oplossingen die bedrijfssucces stimuleren. Onze toewijding aan excellentie, innovatie en klanttevredenheid onderscheidt ons.',
    'why.fast': 'Razendsnel Leveren',
    'why.fastDesc': 'Agile methodologieën zorgen voor snelle ontwikkeling zonder kwaliteit in te boeten',
    'why.business': 'Bedrijfsgerichte Oplossingen',
    'why.businessDesc': 'We stemmen technologie af op uw bedrijfsdoelen voor maximale ROI',
    'why.dedicated': 'Toegewijde Ondersteuning',
    'why.dedicatedDesc': '24/7 ondersteuning en onderhoud om uw systemen soepel te laten draaien',
    'why.innovation': 'Innovatie Eerst',
    'why.innovationDesc': 'Cutting-edge technologie en creatief probleemoplossen',
    'why.successRate': 'Succespercentage',
    'why.yearsInBusiness': 'Jaar in Bedrijf',
    
    // Tech Stack
    'tech.tag': 'Technologie Stack',
    'tech.title': 'Gebouwd met Toonaangevende Technologieën',
    'tech.subtitle': 'We maken gebruik van de nieuwste en meest betrouwbare technologieën om robuuste, schaalbare oplossingen te bouwen',
    
    // Testimonials
    'testimonials.tag': 'Klantbeoordelingen',
    'testimonials.title': 'Wat Onze Klanten Zeggen',
    'testimonials.subtitle': 'Geloof ons niet zomaar—hoor van de bedrijven die we hebben helpen transformeren',
    'testimonials.test1.content': 'TEKFINITY transformeerde onze legacy systemen naar een modern, schaalbaar platform. Hun expertise en toewijding zijn ongeëvenaard.',
    'testimonials.test2.content': 'Werken met TEKFINITY was een gamechanger. Ze leverden onze mobiele app voor schema met uitzonderlijke kwaliteit.',
    'testimonials.test3.content': 'De technische kennis en samenwerkende aanpak van het team maakten ons complexe project tot een succes. Sterk aanbevolen!',
    
    // CTA
    'cta.tag': 'Klaar om te Beginnen?',
    'cta.title': 'Laten We Samen Iets',
    'cta.titleHighlight': 'Buitengewoons Bouwen',
    'cta.subtitle': 'Transformeer uw visie naar werkelijkheid met ons expert team. Plan een gratis consultatie om uw project vandaag te bespreken.',
    'cta.start': 'Start Uw Project',
    'cta.contact': 'Contact Verkoop',
    
    // Features
    'features.do.title': 'Wat we doen',
    'features.do.desc': 'Uitgebreide software engineering diensten op maat gemaakt voor uw bedrijfsbehoeften',
    'features.do.link': 'Ontdek onze diensten',
    'features.think.title': 'Wat we denken',
    'features.think.desc': 'Industrie-inzichten, thought leadership en innovatieve perspectieven',
    'features.think.link': 'Lees onze inzichten',
    'features.who.title': 'Wie we zijn',
    'features.who.desc': 'Maak kennis met het team dat digitale transformatie stimuleert in Nederland',
    'features.who.link': 'Over TEKFINITY',
    
    // Footer
    'footer.about': 'Over TEKFINITY',
    'footer.aboutUs': 'Over Ons',
    'footer.leadership': 'Leiderschap',
    'footer.careers': 'Carrières',
    'footer.newsroom': 'Nieuwskamer',
    'footer.investor': 'Investeerdersrelaties',
    'footer.services': 'Diensten',
    'footer.strategy': 'Strategie & Consultancy',
    'footer.technology': 'Technologie',
    'footer.operations': 'Operaties',
    'footer.industry': 'Brancheoplossingen',
    'footer.insights': 'Inzichten',
    'footer.research': 'Onderzoek & Inzichten',
    'footer.caseStudies': 'Casestudies',
    'footer.blogs': 'Blogs',
    'footer.podcasts': 'Podcasts',
    'footer.resources': 'Bronnen',
    'footer.clients': 'Klanten',
    'footer.partners': 'Partners',
    'footer.suppliers': 'Leveranciers',
    'footer.contactUs': 'Contact',
    'footer.privacy': 'Privacyverklaring',
    'footer.terms': 'Gebruiksvoorwaarden',
    'footer.cookies': 'Cookiebeleid',
    'footer.rights': '© 2025 TEKFINITY',
    
    // Services Page
    'services.hero.title': 'Wat We Doen',
    'services.hero.subtitle': 'Uitgebreide software engineering diensten om uw bedrijf te transformeren',
    'services.custom.title': 'Maatwerk Software',
    'services.custom.desc': 'Op maat gemaakte oplossingen perfect afgestemd op uw unieke bedrijfsbehoeften',
    'services.consulting.title': 'Technische Consultancy',
    'services.consulting.desc': 'Expert advies om uw technologiestrategie te optimaliseren',
    'services.process.title': 'Ons Proces',
    'services.process.subtitle': 'Van concept tot oplevering volgen we een bewezen aanpak die kwaliteit en succes garandeert',
    'services.process.step1.title': 'Ontdekking',
    'services.process.step1.desc': 'We beginnen met het begrijpen van uw doelen, uitdagingen en visie',
    'services.process.step2.title': 'Strategie',
    'services.process.step2.desc': 'Ontwikkel een technische roadmap afgestemd op uw bedrijfsdoelen',
    'services.process.step3.title': 'Ontwikkeling',
    'services.process.step3.desc': 'Bouwen van schaalbare, hoogwaardige oplossingen met agile methodologieën',
    'services.process.step4.title': 'Oplevering',
    'services.process.step4.desc': 'Naadloze implementatie met voortdurende ondersteuning en optimalisatie',
    'services.cta.title': 'Klaar om uw project te starten?',
    'services.cta.desc': 'Neem vandaag nog contact met ons op om te bespreken hoe wij uw bedrijf kunnen helpen',
    
    // Insights Page
    'insights.hero.title': 'Wat We Denken',
    'insights.hero.subtitle': 'Industrie-inzichten, onderzoek en thought leadership',
    'insights.featured': 'UITGELICHT',
    'insights.featured.title': 'De Toekomst van Software Engineering in 2025',
    'insights.featured.desc': 'Ontdek hoe AI, cloud-native architectuur en moderne ontwikkelpraktijken de industrie herdefiniëren.',
    'insights.readMore': 'Lees meer',
    'insights.latest': 'Laatste Inzichten',
    
    // About Page
    'about.hero.title': 'Wie We Zijn',
    'about.hero.subtitle': 'Een team van gepassioneerde innovators die digitale transformatie stimuleren',
    'about.story.title': 'Ons Verhaal',
    'about.story.p1': 'TEKFINITY werd opgericht met één missie: de kloof overbruggen tussen bedrijfsdoelen en technologische innovatie. Vanaf dag één hebben we ons gericht op het leveren van software engineering excellence.',
    'about.story.p2': 'Vandaag werken we met toonaangevende organisaties in Nederland, waarbij we digitale transformatie stimuleren door middel van cutting-edge technologie en ongeëvenaarde expertise.',
    'about.story.p3': 'Met een team van meer dan 150 getalenteerde engineers, designers en consultants leveren we innovatieve oplossingen die echte bedrijfswaarde creëren. Onze klanten kiezen ons vanwege onze bewezen trackrecord, technische expertise en onwrikbare toewijding aan hun succes.',
    'about.values.title': 'Onze Waarden',
    'about.values.subtitle': 'De principes die ons werk leiden',
    'about.values.mission.title': 'Onze Missie',
    'about.values.mission.desc': 'Bedrijven empoweren met innovatieve softwareoplossingen',
    'about.values.team.title': 'Ons Team',
    'about.values.team.desc': 'Talentvolle professionals toegewijd aan excellentie',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Altijd streven naar de hoogste kwaliteitsnormen',
    'about.values.innovation.title': 'Innovatie',
    'about.values.innovation.desc': 'De grenzen van wat mogelijk is verleggen',
    
    // Careers Page
    'careers.hero.title': 'Carrières bij TEKFINITY',
    'careers.hero.subtitle': 'Word deel van een team dat de toekomst van software engineering vormt',
    'careers.benefits.title': 'Waarom bij ons werken?',
    'careers.benefits.learning': '🎓 Continue leer- en ontwikkelingsmogelijkheden',
    'careers.benefits.balance': '⚖️ Werk-privébalans en flexibele werktijden',
    'careers.benefits.health': '🏥 Uitgebreid gezondheids- en wellnessprogramma',
    'careers.benefits.remote': '🌍 Remote werk opties',
    'careers.benefits.growth': '📈 Duidelijke carrièrepaden en groei',
    'careers.benefits.culture': '🤝 Collaboratieve en inclusieve cultuur',
    'careers.openings.title': 'Open Posities',
    'careers.job1.title': 'Senior Full-Stack Developer',
    'careers.job1.location': 'Amsterdam',
    'careers.job1.type': 'Fulltime',
    'careers.job1.department': 'Engineering',
    'careers.job2.title': 'Cloud Architect',
    'careers.job2.location': 'Rotterdam',
    'careers.job2.type': 'Fulltime',
    'careers.job2.department': 'Infrastructure',
    'careers.job3.title': 'AI/ML Engineer',
    'careers.job3.location': 'Utrecht',
    'careers.job3.type': 'Fulltime',
    'careers.job3.department': 'AI & Data',
    'careers.job4.title': 'UX/UI Designer',
    'careers.job4.location': 'Amsterdam',
    'careers.job4.type': 'Fulltime',
    'careers.job4.department': 'Design',
    'careers.apply': 'Solliciteer nu',
    'careers.culture.title': 'Onze Cultuur',
    'careers.culture.subtitle': 'Bij TEKFINITY geloven we dat geweldige producten worden gemaakt door geweldige teams',
    'careers.culture.innovation.title': 'Innovatie Gedreven',
    'careers.culture.innovation.desc': 'We moedigen creativiteit aan en verwelkomen nieuwe ideeën van iedereen',
    'careers.culture.collaboration.title': 'Collaboratief',
    'careers.culture.collaboration.desc': 'Teamwork en open communicatie staan centraal in alles wat we doen',
    'careers.culture.growth.title': 'Groeifocus',
    'careers.culture.growth.desc': 'Continue leren en ontwikkeling zijn kernwaarden van ons team',
    'careers.cta.title': 'Zie je jezelf niet in deze rollen?',
    'careers.cta.desc': 'We zijn altijd op zoek naar getalenteerde mensen. Stuur ons je CV!',
    'careers.cta.button': 'Stuur Open Sollicitatie',
    
    // Articles
    'articles.notFound': 'Artikel niet gevonden',
    'articles.backToInsights': 'Terug naar Inzichten',
    'articles.back': 'Terug naar inzichten',
    'articles.ai.title': 'Digitale Transformatie: Van complexiteit beheren tot groei versnellen',
    'articles.ai.content': 'Digitale transformatie is niet alleen een technologie-strategie—het is een gamechanger voor bedrijfsconcurrentievermogen. In de snel veranderende zakelijke omgeving van vandaag zoeken organisaties naar manieren om hun concurrentievoordeel te behouden door digitale technologieën te omarmen. Deze transformatie gaat verder dan alleen het implementeren van nieuwe tools; het vereist een fundamentele verschuiving in hoe bedrijven opereren en waarde leveren aan hun klanten.|Het succesvol navigeren van digitale transformatie vereist een strategische aanpak die technologie, mensen en processen in balans brengt. Organisaties die excelleren in deze reis beginnen met een duidelijke visie en routekaart, die is afgestemd op hun bredere bedrijfsdoelstellingen. Ze investeren in het opbouwen van digitale capaciteiten in hun teams en creëren een cultuur die innovatie en experimenteren omarmt.|Een van de grootste uitdagingen in digitale transformatie is het omgaan met legacy systemen en processen. Veel organisaties worstelen met het in balans brengen van de behoefte aan snelle innovatie met de realiteit van bestaande infrastructuur. De sleutel is het adopteren van een geleidelijke modernisatieaanpak die zowel de eisen van vandaag als de ambities van morgen aanpakt.|De rol van data en analytics in digitale transformatie kan niet worden overschat. Organisaties die hun data als een strategische asset behandelen zijn beter gepositioneerd om geïnformeerde beslissingen te nemen, operaties te optimaliseren en nieuwe kansen te identificeren. Dit vereist investering in data infrastructuur, analytics tools en—misschien het meest belangrijke—datavaardigheden in het gehele bedrijf.|Concluderend, digitale transformatie is een reis, geen bestemming. Organisaties die het adopteren als een continue proces van leren, experimenteren en aanpassen zijn beter gepositioneerd om te slagen in het digitale tijdperk. De focus moet liggen op het leveren van tastbare bedrijfswaarde terwijl capaciteiten worden opgebouwd voor toekomstige innovatie.',
    'articles.cloud.title': 'Moderne Ontwikkeling 2025: De toekomst van agile software engineering',
    'articles.cloud.content': 'De landschap van software ontwikkeling evolueert in een ongekend tempo. Ontwikkelteams worden geconfronteerd met toenemende complexiteit, snelle technologische verandering, en stijgende verwachtingen voor snellere levering. In deze omgeving wordt het adopteren van moderne ontwikkelpraktijken niet alleen een concurrentievoordeel—het wordt een noodzaak voor overleven.|Moderne software ontwikkeling is gebouwd op principes van agility, automation, en continue verbetering. Teams die deze praktijken omarmen kunnen sneller waarde leveren, responsiever zijn aan veranderende requirements, en betere kwaliteitsstandaarden handhaven. De shift naar cloud-native architecturen en microservices heeft teams in staat gesteld om meer flexibele en schaalbare systemen te bouwen.|DevOps en continuous integration/continuous deployment (CI/CD) zijn kernpraktijken geworden in moderne ontwikkeling. Deze benaderingen breken traditionele silo\'s tussen ontwikkel- en operationele teams af, enabling snellere en betrouwbaardere software releases. Automation van testing, deployment, en infrastructuur management vermindert handmatige fouten en bevrijdt teams om te focussen op het leveren van waarde.|De toename van AI en machine learning in ontwikkeltools transformeert hoe ontwikkelaars werken. Van intelligente code completion tot automated testing en bug detectie, AI-aangedreven tools verbeteren productiviteit en code kwaliteit. Echter, het succesvol integreren van deze tools vereist een doordachte aanpak die menselijke expertise versterkt in plaats van vervangt.|Kijkend naar de toekomst is het duidelijk dat software ontwikkeling zal blijven evolueren. Succesvolle teams zijn degenen die een leermindset handhaven, experimenteren met nieuwe praktijken en tools, en hun benaderingen blijven aanpassen gebaseerd op resultaten. De focus moet altijd blijven op het leveren van waarde aan gebruikers terwijl code kwaliteit en team welzijn behouden blijven.',
    'articles.digital.title': 'Enterprise Oplossingen: Platforms bouwen voor morgen',
    'articles.digital.content': 'Enterprise organisaties staan voor unieke uitdagingen als het gaat om het moderniseren van hun technologie landscape. Decennia van investering in legacy systemen heeft een complexe web van applications, databases, en integrations gecreëerd die kritische bedrijfsoperaties ondersteunen. De uitdaging ligt in het transformeren van deze systemen zonder bestaande operaties te ontwrichten.|Moderne enterprise platforms zijn gebouwd op principes van modulariteit, schaalbaarheid, en flexibiliteit. In plaats van monolithische applicaties, zijn organisaties steeds meer aan het shiften naar microservices architecturen die independent ontwikkeling, deployment, en scaling van verschillende componenten toestaan. Deze aanpak enables grotere agiliteit en reduceert risico\'s geassocieerd met systeemveranderingen.|API-eerste ontwerp is een cruciaal aspect geworden van enterprise platform strategie. Door services te ontwerpen rond goed-gedefinieerde APIs, kunnen organisaties flexibelere en herbruikbaardere componenten creëren die gemakkelijk kunnen worden geïntegreerd met andere systemen. Deze aanpak faciliteert ook betere samenwerking tussen teams en enables snellere innovatie.|De rol van cloud computing in enterprise modernisatie kan niet worden overschat. Cloud platforms bieden de schaalbaarheid, betrouwbaarheid, en beveiliging die enterprise applicaties vereisen, terwijl ze ook innovatie versnellen door toegang tot geavanceerde services zoals AI, machine learning, en data analytics. De shift naar de cloud is echter niet alleen technisch—het vereist organisatorische verandering en nieuwe vaardigheden.|Kijkend vooruit, succesvol enterprise platforms zijn gebouwd met een eye op toekomstige evolutie. Dit betekent investeren in architecturen die verandering kunnen accommoderen, standards adopterende die interoperabiliteit enablen, en een cultuur van continue verbetering creëren. De focus moet liggen op het leveren van consistente waarde terwijl flexibiliteit wordt behouden om aan te passen als zakelijke behoeften evolueren.',
    'articles.future.title': 'Innovatie Versneld: Mens-AI samenwerking in software',
    'articles.future.content': 'De opkomst van kunstmatige intelligentie in software ontwikkeling markeert een fundamentele verschuiving in hoe we applicaties bouwen en leveren. AI is niet langer alleen een feature in software—het wordt een core partner in het ontwikkelproces zelf. Deze transformatie biedt zowel opwindende kansen als belangrijke uitdagingen voor ontwikkelteams wereldwijd.|AI-aangedreven ontwikkeltools zijn snel geëvolueerd van eenvoudige code completion naar geavanceerde assistenten die kunnen helpen met complex probleemoplossen, code reviews, en zelfs architectureel ontwerp. Deze tools verbeteren ontwikkelaar productiviteit door routine taken te automatiseren, bugs te helpen identificeren, en design patterns te suggereren. Echter, hun effectiviteit is afhankelijk van ontwikkelaars die begrijpen wanneer en hoe ze effectief te gebruiken.|Het snijvlak van menselijke creativiteit en AI capabilities is waar echte innovatie gebeurt. Terwijl AI excelleert in patroonherkenning en het genereren van opties gebaseerd op grote datasets, brengen mensen kritiek denken, creativiteit, en een begrip van bedrijfscontext. De meest succesvolle teams zijn degenen die leren AI te leveragen voor waar het excelleert terwijl menselijke expertise in strategische besluitvorming behouden blijft.|Ethische overwegingen zijn paramount als AI een groter onderdeel wordt van software ontwikkeling. Vragen over bias in AI-generated code, data privacy, en de impact op ontwikkelaar rollen moeten zorgvuldig worden overwogen. Organisaties moeten richtlijnen en best practices ontwikkelen voor verantwoorde AI gebruik in hun ontwikkelprocessen.|De toekomst van software ontwikkeling zal ongetwijfeld steeds meer AI-verrijkt zijn. Echter, in plaats van ontwikkelaars te vervangen, is AI waarschijnlijker hun capaciteiten te versterken, enabling ze om te focussen op hoger niveau problemen en creatiever werk. De sleutel tot succes is het omarmen van deze technologieën terwijl menselijke expertise en oordeel centraal behouden blijven in het ontwikkelproces.',
    
    // Search
    'search.title': 'Zoeken',
    'search.placeholder': 'Zoek naar diensten, inzichten, vacatures...',
    'search.empty': 'Begin met typen om te zoeken',
    'search.noResults': 'Geen resultaten gevonden',
    
    // Contact Page
    'contact.hero.title': 'Neem Contact Op',
    'contact.hero.subtitle': 'Klaar om uw project te starten? Neem vandaag nog contact met ons op voor een consultatie.',
    'contact.form.title': 'Stuur ons een bericht',
    'contact.form.name': 'Uw naam',
    'contact.form.email': 'Uw e-mail',
    'contact.form.subject': 'Onderwerp',
    'contact.form.message': 'Uw bericht',
    'contact.form.submit': 'Verstuur bericht',
    'contact.form.sending': 'Verzenden...',
    'contact.info.title': 'Contactgegevens',
    'contact.phone': 'Telefoon',
    'contact.location': 'Locatie',
    'contact.success.title': 'Bericht verzonden!',
    'contact.success.description': 'We nemen zo snel mogelijk contact met u op.',
    'contact.error.title': 'Fout',
    'contact.error.description': 'Er is iets misgegaan. Probeer het later opnieuw.',
    'contact.cta.title': 'Heeft u een project idee?',
    'contact.cta.description': 'Start uw project met onze intuïtieve wizard en vertel ons over uw wensen.',
    'contact.cta.button': 'Start Project Wizard',
    
    // Start Project Page
    'startProject.badge': 'Project Starten',
    'startProject.hero.title': 'Vertel ons over uw droomproject',
    'startProject.hero.subtitle': 'In slechts een paar stappen helpen we u uw visie te realiseren',
    'startProject.steps.contact': 'Contact',
    'startProject.steps.services': 'Services',
    'startProject.steps.details': 'Details',
    'startProject.steps.description': 'Beschrijving',
    'startProject.step1.title': 'Laten we kennis maken',
    'startProject.step1.subtitle': 'Vertel ons hoe we u kunnen bereiken',
    'startProject.step2.title': 'Wat heeft u nodig?',
    'startProject.step2.subtitle': 'Selecteer de services die u interesseren',
    'startProject.step3.title': 'Project Details',
    'startProject.step3.subtitle': 'Help ons uw project beter te begrijpen',
    'startProject.step4.title': 'Vertel uw verhaal',
    'startProject.step4.subtitle': 'Beschrijf uw project en visie in detail',
    'startProject.form.name': 'Naam',
    'startProject.form.email': 'E-mail',
    'startProject.form.company': 'Bedrijf (optioneel)',
    'startProject.form.budget': 'Budget',
    'startProject.form.timeline': 'Timeline',
    'startProject.form.description': 'Project beschrijving',
    'startProject.form.descriptionPlaceholder': 'Vertel ons over uw project. Wat wilt u bouwen? Welke problemen wilt u oplossen? Wie zijn uw gebruikers?',
    'startProject.form.minChars': 'minimaal karakters',
    'startProject.navigation.back': 'Terug',
    'startProject.navigation.next': 'Volgende',
    'startProject.navigation.submit': 'Verstuur Aanvraag',
    'startProject.navigation.submitting': 'Verzenden...',
    'startProject.success.title': 'Aanvraag verzonden!',
    'startProject.success.description': 'We hebben uw project aanvraag ontvangen en nemen binnen 24 uur contact met u op.',
    'startProject.error.title': 'Fout',
    'startProject.error.description': 'Er is iets misgegaan. Probeer het later opnieuw.',
  },
  en: {
    // Navigation
    'nav.services': 'What we do',
    'nav.insights': 'What we think',
    'nav.about': 'Who we are',
    'nav.careers': 'Careers',
    'nav.country': 'Netherlands',
    
    // Hero
    'hero.title': 'TOGETHER WE BUILD',
    'hero.titleHighlight': 'THE FUTURE',
    'hero.subtitle': 'Scaling Software Solutions',
    'hero.description': 'We help clients prioritize business strategy, technology readiness and organizational readiness to get to value faster.',
    'hero.cta': 'See what we do',
    
    // Stats
    'stats.title': 'Trusted by Leading Organizations',
    'stats.subtitle': 'Our track record speaks for itself',
    'stats.clients.number': '500+',
    'stats.clients.label': 'Clients Served',
    'stats.clients.desc': 'Across the Netherlands',
    'stats.satisfaction.number': '98%',
    'stats.satisfaction.label': 'Client Satisfaction',
    'stats.satisfaction.desc': 'Industry-leading retention',
    'stats.projects.number': '250+',
    'stats.projects.label': 'Projects Delivered',
    'stats.projects.desc': 'On time and on budget',
    'stats.experience.number': '15+',
    'stats.experience.label': 'Years Experience',
    'stats.experience.desc': 'In software engineering',
    
    // Cards
    'cards.report': 'RESEARCH REPORT',
    'cards.case': 'CASE STUDY',
    'cards.card1.title': 'Digital Transformation: From managing complexity to accelerating growth',
    'cards.card1.desc': "Digital transformation isn't just a technology play—it's a game-changer for business competitiveness. Discover how organizations are moving fast to secure their advantage.",
    'cards.card2.title': 'Modern Development 2025: The future of agile software engineering',
    'cards.card2.desc': 'Development teams, facing complexity and rapid change, are seeking efficiency combined with innovation, scalability and connection.',
    'cards.card3.title': 'Enterprise Solutions: Building platforms for tomorrow',
    'cards.card3.desc': 'How leading companies are transforming their legacy systems into modern, scalable platforms that drive business value.',
    'cards.card4.title': 'Innovation Accelerated: Human-AI collaboration in software',
    'cards.card4.desc': 'Exploring the intersection of human creativity and AI capabilities to revolutionize how we build software solutions.',
    
    // Services Showcase
    'servicesShowcase.tag': 'Our Expertise',
    'servicesShowcase.title': 'Comprehensive Software Solutions',
    'servicesShowcase.subtitle': 'From concept to deployment, we deliver end-to-end software engineering services that drive innovation and business growth',
    'servicesShowcase.mobile': 'Mobile App Development',
    'servicesShowcase.mobileDesc': 'Native iOS & Android apps with cutting-edge features and seamless UX',
    'servicesShowcase.web': 'Web Development',
    'servicesShowcase.webDesc': 'Modern, responsive web applications built with the latest frameworks',
    'servicesShowcase.cloud': 'Cloud Solutions',
    'servicesShowcase.cloudDesc': 'Scalable cloud infrastructure and migration services',
    'servicesShowcase.ai': 'AI & Machine Learning',
    'servicesShowcase.aiDesc': 'Intelligent solutions powered by advanced AI algorithms',
    'servicesShowcase.data': 'Data Engineering',
    'servicesShowcase.dataDesc': 'Big data solutions and analytics for data-driven decisions',
    'servicesShowcase.security': 'Cybersecurity',
    'servicesShowcase.securityDesc': 'Enterprise-grade security solutions to protect your assets',
    
    // Why Choose Us
    'why.tag': 'Why Choose TEKFINITY',
    'why.title': 'Excellence in Every Line of Code',
    'why.subtitle': "We don't just write code—we craft solutions that drive business success. Our commitment to excellence, innovation, and client satisfaction sets us apart.",
    'why.fast': 'Lightning Fast Delivery',
    'why.fastDesc': 'Agile methodologies ensure rapid development without compromising quality',
    'why.business': 'Business-Focused Solutions',
    'why.businessDesc': 'We align technology with your business goals for maximum ROI',
    'why.dedicated': 'Dedicated Support',
    'why.dedicatedDesc': '24/7 support and maintenance to keep your systems running smoothly',
    'why.innovation': 'Innovation First',
    'why.innovationDesc': 'Cutting-edge technology and creative problem-solving',
    'why.successRate': 'Success Rate',
    'why.yearsInBusiness': 'Years in Business',
    
    // Tech Stack
    'tech.tag': 'Technology Stack',
    'tech.title': 'Built with Industry-Leading Technologies',
    'tech.subtitle': 'We leverage the latest and most reliable technologies to build robust, scalable solutions',
    
    // Testimonials
    'testimonials.tag': 'Client Testimonials',
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': "Don't just take our word for it - hear from the companies we've helped transform",
    'testimonials.test1.content': 'TEKFINITY transformed our legacy systems into a modern, scalable platform. Their expertise and dedication are unmatched.',
    'testimonials.test2.content': 'Working with TEKFINITY was a game-changer. They delivered our mobile app ahead of schedule with exceptional quality.',
    'testimonials.test3.content': "The team's technical knowledge and collaborative approach made our complex project a success. Highly recommended!",
    
    // CTA
    'cta.tag': 'Ready to Get Started?',
    'cta.title': "Let's Build Something",
    'cta.titleHighlight': 'Extraordinary Together',
    'cta.subtitle': 'Transform your vision into reality with our expert team. Schedule a free consultation to discuss your project today.',
    'cta.start': 'Start Your Project',
    'cta.contact': 'Contact Sales',
    
    // Features
    'features.do.title': 'What we do',
    'features.do.desc': 'Comprehensive software engineering services tailored to your business needs',
    'features.do.link': 'Explore our services',
    'features.think.title': 'What we think',
    'features.think.desc': 'Industry insights, thought leadership, and innovative perspectives',
    'features.think.link': 'Read our insights',
    'features.who.title': 'Who we are',
    'features.who.desc': 'Meet the team driving digital transformation across the Netherlands',
    'features.who.link': 'About TEKFINITY',
    
    // Footer
    'footer.about': 'About TEKFINITY',
    'footer.aboutUs': 'About Us',
    'footer.leadership': 'Leadership',
    'footer.careers': 'Careers',
    'footer.newsroom': 'Newsroom',
    'footer.investor': 'Investor Relations',
    'footer.services': 'Services',
    'footer.strategy': 'Strategy & Consulting',
    'footer.technology': 'Technology',
    'footer.operations': 'Operations',
    'footer.industry': 'Industry Solutions',
    'footer.insights': 'Insights',
    'footer.research': 'Research & Insights',
    'footer.caseStudies': 'Case Studies',
    'footer.blogs': 'Blogs',
    'footer.podcasts': 'Podcasts',
    'footer.resources': 'Resources',
    'footer.clients': 'Clients',
    'footer.partners': 'Partners',
    'footer.suppliers': 'Suppliers',
    'footer.contactUs': 'Contact Us',
    'footer.privacy': 'Privacy Statement',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookie Policy',
    'footer.rights': '© 2025 TEKFINITY',
    
    // Services Page
    'services.hero.title': 'What We Do',
    'services.hero.subtitle': 'Comprehensive software engineering services to transform your business',
    'services.custom.title': 'Custom Software',
    'services.custom.desc': 'Tailored solutions perfectly aligned with your unique business needs',
    'services.consulting.title': 'Technical Consulting',
    'services.consulting.desc': 'Expert guidance to optimize your technology strategy',
    'services.process.title': 'Our Process',
    'services.process.subtitle': 'From concept to delivery, we follow a proven approach that ensures quality and success',
    'services.process.step1.title': 'Discovery',
    'services.process.step1.desc': 'We begin by understanding your goals, challenges, and vision',
    'services.process.step2.title': 'Strategy',
    'services.process.step2.desc': 'Develop a technical roadmap aligned with your business objectives',
    'services.process.step3.title': 'Development',
    'services.process.step3.desc': 'Build scalable, high-quality solutions using agile methodologies',
    'services.process.step4.title': 'Delivery',
    'services.process.step4.desc': 'Seamless deployment with ongoing support and optimization',
    'services.cta.title': 'Ready to start your project?',
    'services.cta.desc': 'Get in touch with us today to discuss how we can help your business',
    
    // Insights Page
    'insights.hero.title': 'What We Think',
    'insights.hero.subtitle': 'Industry insights, research, and thought leadership',
    'insights.featured': 'FEATURED',
    'insights.featured.title': 'The Future of Software Engineering in 2025',
    'insights.featured.desc': 'Explore how AI, cloud-native architecture, and modern development practices are redefining the industry.',
    'insights.readMore': 'Read more',
    'insights.latest': 'Latest Insights',
    
    // About Page
    'about.hero.title': 'Who We Are',
    'about.hero.subtitle': 'A team of passionate innovators driving digital transformation',
    'about.story.title': 'Our Story',
    'about.story.p1': 'TEKFINITY was founded with one mission: to bridge the gap between business objectives and technological innovation. From day one, we\'ve focused on delivering software engineering excellence.',
    'about.story.p2': 'Today, we work with leading organizations across the Netherlands, driving digital transformation through cutting-edge technology and unmatched expertise.',
    'about.story.p3': 'With a team of over 150 talented engineers, designers, and consultants, we deliver innovative solutions that create real business value. Our clients choose us for our proven track record, technical expertise, and unwavering commitment to their success.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide our work',
    'about.values.mission.title': 'Our Mission',
    'about.values.mission.desc': 'Empowering businesses with innovative software solutions',
    'about.values.team.title': 'Our Team',
    'about.values.team.desc': 'Talented professionals dedicated to excellence',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Always striving for the highest standards of quality',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Pushing the boundaries of what\'s possible',
    
    // Careers Page
    'careers.hero.title': 'Careers at TEKFINITY',
    'careers.hero.subtitle': 'Join a team that\'s shaping the future of software engineering',
    'careers.benefits.title': 'Why Work With Us?',
    'careers.benefits.learning': '🎓 Continuous learning and development opportunities',
    'careers.benefits.balance': '⚖️ Work-life balance and flexible hours',
    'careers.benefits.health': '🏥 Comprehensive health and wellness program',
    'careers.benefits.remote': '🌍 Remote work options',
    'careers.benefits.growth': '📈 Clear career paths and advancement',
    'careers.benefits.culture': '🤝 Collaborative and inclusive culture',
    'careers.openings.title': 'Open Positions',
    'careers.job1.title': 'Senior Full-Stack Developer',
    'careers.job1.location': 'Amsterdam',
    'careers.job1.type': 'Full-time',
    'careers.job1.department': 'Engineering',
    'careers.job2.title': 'Cloud Architect',
    'careers.job2.location': 'Rotterdam',
    'careers.job2.type': 'Full-time',
    'careers.job2.department': 'Infrastructure',
    'careers.job3.title': 'AI/ML Engineer',
    'careers.job3.location': 'Utrecht',
    'careers.job3.type': 'Full-time',
    'careers.job3.department': 'AI & Data',
    'careers.job4.title': 'UX/UI Designer',
    'careers.job4.location': 'Amsterdam',
    'careers.job4.type': 'Full-time',
    'careers.job4.department': 'Design',
    'careers.apply': 'Apply now',
    'careers.culture.title': 'Our Culture',
    'careers.culture.subtitle': 'At TEKFINITY, we believe great products are built by great teams',
    'careers.culture.innovation.title': 'Innovation Driven',
    'careers.culture.innovation.desc': 'We encourage creativity and welcome new ideas from everyone',
    'careers.culture.collaboration.title': 'Collaborative',
    'careers.culture.collaboration.desc': 'Teamwork and open communication are at the heart of everything we do',
    'careers.culture.growth.title': 'Growth Focused',
    'careers.culture.growth.desc': 'Continuous learning and development are core values of our team',
    'careers.cta.title': "Don't see yourself in these roles?",
    'careers.cta.desc': "We're always looking for talented people. Send us your CV!",
    'careers.cta.button': 'Send Open Application',
    
    // Articles
    'articles.notFound': 'Article not found',
    'articles.backToInsights': 'Back to Insights',
    'articles.back': 'Back to insights',
    'articles.ai.title': 'Digital Transformation: From managing complexity to accelerating growth',
    'articles.ai.content': "Digital transformation isn't just a technology play—it's a game-changer for business competitiveness. In today's rapidly evolving business landscape, organizations are seeking ways to maintain their competitive edge by embracing digital technologies. This transformation goes beyond simply implementing new tools; it requires a fundamental shift in how businesses operate and deliver value to their customers.|Successfully navigating digital transformation requires a strategic approach that balances technology, people, and processes. Organizations that excel in this journey start with a clear vision and roadmap, aligned with their broader business objectives. They invest in building digital capabilities across their teams and create a culture that embraces innovation and experimentation.|One of the biggest challenges in digital transformation is managing legacy systems and processes. Many organizations struggle with balancing the need for rapid innovation with the reality of existing infrastructure. The key is adopting a phased modernization approach that addresses both today's requirements and tomorrow's ambitions.|The role of data and analytics in digital transformation cannot be overstated. Organizations that treat their data as a strategic asset are better positioned to make informed decisions, optimize operations, and identify new opportunities. This requires investment in data infrastructure, analytics tools, and—perhaps most importantly—data literacy across the organization.|In conclusion, digital transformation is a journey, not a destination. Organizations that embrace it as a continuous process of learning, experimentation, and adaptation are better positioned to thrive in the digital age. The focus must be on delivering tangible business value while building capabilities for future innovation.",
    'articles.cloud.title': 'Modern Development 2025: The future of agile software engineering',
    'articles.cloud.content': 'The landscape of software development is evolving at an unprecedented pace. Development teams are facing increasing complexity, rapid technological change, and rising expectations for faster delivery. In this environment, adopting modern development practices isn\'t just a competitive advantage—it\'s becoming a necessity for survival.|Modern software development is built on principles of agility, automation, and continuous improvement. Teams that embrace these practices can deliver value faster, be more responsive to changing requirements, and maintain higher quality standards. The shift toward cloud-native architectures and microservices has enabled teams to build more flexible and scalable systems.|DevOps and continuous integration/continuous deployment (CI/CD) have become core practices in modern development. These approaches break down traditional silos between development and operations teams, enabling faster and more reliable software releases. Automation of testing, deployment, and infrastructure management reduces manual errors and frees teams to focus on delivering value.|The rise of AI and machine learning in development tools is transforming how developers work. From intelligent code completion to automated testing and bug detection, AI-powered tools are enhancing productivity and code quality. However, successfully integrating these tools requires a thoughtful approach that augments rather than replaces human expertise.|Looking ahead, it\'s clear that software development will continue to evolve. Successful teams will be those that maintain a learning mindset, experiment with new practices and tools, and continuously adapt their approaches based on results. The focus must always remain on delivering value to users while maintaining code quality and team well-being.',
    'articles.digital.title': 'Enterprise Solutions: Building platforms for tomorrow',
    'articles.digital.content': 'Enterprise organizations face unique challenges when it comes to modernizing their technology landscape. Decades of investment in legacy systems have created a complex web of applications, databases, and integrations that support critical business operations. The challenge lies in transforming these systems without disrupting existing operations.|Modern enterprise platforms are built on principles of modularity, scalability, and flexibility. Rather than monolithic applications, organizations are increasingly shifting toward microservices architectures that allow independent development, deployment, and scaling of different components. This approach enables greater agility and reduces the risks associated with system changes.|API-first design has become a crucial aspect of enterprise platform strategy. By designing services around well-defined APIs, organizations can create more flexible and reusable components that can easily be integrated with other systems. This approach also facilitates better collaboration between teams and enables faster innovation.|The role of cloud computing in enterprise modernization cannot be overstated. Cloud platforms provide the scalability, reliability, and security that enterprise applications require, while also accelerating innovation through access to advanced services like AI, machine learning, and data analytics. However, the shift to the cloud isn\'t just technical—it requires organizational change and new skills.|Looking forward, successful enterprise platforms are built with an eye toward future evolution. This means investing in architectures that can accommodate change, adopting standards that enable interoperability, and creating a culture of continuous improvement. The focus must be on delivering consistent value while maintaining flexibility to adapt as business needs evolve.',
    'articles.future.title': 'Innovation Accelerated: Human-AI collaboration in software',
    'articles.future.content': 'The rise of artificial intelligence in software development marks a fundamental shift in how we build and deliver applications. AI is no longer just a feature in software—it\'s becoming a core partner in the development process itself. This transformation presents both exciting opportunities and important challenges for development teams worldwide.|AI-powered development tools have rapidly evolved from simple code completion to sophisticated assistants that can help with complex problem-solving, code reviews, and even architectural design. These tools enhance developer productivity by automating routine tasks, helping identify bugs, and suggesting design patterns. However, their effectiveness depends on developers understanding when and how to use them effectively.|The intersection of human creativity and AI capabilities is where true innovation happens. While AI excels at pattern recognition and generating options based on vast datasets, humans bring critical thinking, creativity, and an understanding of business context. The most successful teams are those that learn to leverage AI for what it does well while maintaining human expertise in strategic decision-making.|Ethical considerations are paramount as AI becomes a larger part of software development. Questions about bias in AI-generated code, data privacy, and the impact on developer roles must be carefully considered. Organizations need to develop guidelines and best practices for responsible AI use in their development processes.|The future of software development will undoubtedly be increasingly AI-augmented. However, rather than replacing developers, AI is more likely to amplify their capabilities, enabling them to focus on higher-level problems and more creative work. The key to success is embracing these technologies while keeping human expertise and judgment at the center of the development process.',
    
    // Search
    'search.title': 'Search',
    'search.placeholder': 'Search for services, insights, jobs...',
    'search.empty': 'Start typing to search',
    'search.noResults': 'No results found',
    
    // Contact Page
    'contact.hero.title': 'Get In Touch',
    'contact.hero.subtitle': 'Ready to start your project? Contact us today for a consultation.',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Your name',
    'contact.form.email': 'Your email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Your message',
    'contact.form.submit': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Contact Information',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.success.title': 'Message sent!',
    'contact.success.description': 'We will get back to you as soon as possible.',
    'contact.error.title': 'Error',
    'contact.error.description': 'Something went wrong. Please try again later.',
    'contact.cta.title': 'Have a project idea?',
    'contact.cta.description': 'Start your project with our intuitive wizard and tell us about your wishes.',
    'contact.cta.button': 'Start Project Wizard',
    
    // Start Project Page
    'startProject.badge': 'Start Project',
    'startProject.hero.title': 'Tell us about your dream project',
    'startProject.hero.subtitle': 'In just a few steps, we will help you realize your vision',
    'startProject.steps.contact': 'Contact',
    'startProject.steps.services': 'Services',
    'startProject.steps.details': 'Details',
    'startProject.steps.description': 'Description',
    'startProject.step1.title': "Let's get to know each other",
    'startProject.step1.subtitle': 'Tell us how we can reach you',
    'startProject.step2.title': 'What do you need?',
    'startProject.step2.subtitle': 'Select the services you are interested in',
    'startProject.step3.title': 'Project Details',
    'startProject.step3.subtitle': 'Help us understand your project better',
    'startProject.step4.title': 'Tell your story',
    'startProject.step4.subtitle': 'Describe your project and vision in detail',
    'startProject.form.name': 'Name',
    'startProject.form.email': 'Email',
    'startProject.form.company': 'Company (optional)',
    'startProject.form.budget': 'Budget',
    'startProject.form.timeline': 'Timeline',
    'startProject.form.description': 'Project description',
    'startProject.form.descriptionPlaceholder': 'Tell us about your project. What do you want to build? What problems do you want to solve? Who are your users?',
    'startProject.form.minChars': 'minimum characters',
    'startProject.navigation.back': 'Back',
    'startProject.navigation.next': 'Next',
    'startProject.navigation.submit': 'Submit Request',
    'startProject.navigation.submitting': 'Submitting...',
    'startProject.success.title': 'Request submitted!',
    'startProject.success.description': 'We have received your project request and will contact you within 24 hours.',
    'startProject.error.title': 'Error',
    'startProject.error.description': 'Something went wrong. Please try again later.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('nl');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
